[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 15
offset = { x = 0, y = 3 }

[general]
import = [
    "~/.config/alacritty/themes/frappe.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.3
