[colors.primary]
background = "#0A1017"
foreground = "#b3c6d8"

[colors.cursor]
text = "#0A1017"
cursor = "#b3c6d8"

[colors.normal]
black   = "#0A1017"
red     = "#36506B"
green   = "#3F607F"
yellow  = "#435C76"
blue    = "#3F6081"
magenta = "#517294"
cyan    = "#678AAD"
white   = "#b3c6d8"

[colors.bright]
black   = "#7d8a97"
red     = "#36506B"
green   = "#3F607F"
yellow  = "#435C76"
blue    = "#3F6081"
magenta = "#517294"
cyan    = "#678AAD"
white   = "#b3c6d8"

