[colors.primary]
background = "#0C1732"
foreground = "#c6cbe6"

[colors.cursor]
text = "#0C1732"
cursor = "#c6cbe6"

[colors.normal]
black   = "#0C1732"
red     = "#5E7AC4"
green   = "#827CB4"
yellow  = "#7084BA"
blue    = "#768DC9"
magenta = "#7692DF"
cyan    = "#8899D1"
white   = "#c6cbe6"

[colors.bright]
black   = "#8a8ea1"
red     = "#5E7AC4"
green   = "#827CB4"
yellow  = "#7084BA"
blue    = "#768DC9"
magenta = "#7692DF"
cyan    = "#8899D1"
white   = "#c6cbe6"

