[colors]
[colors.primary]
background = "#ECEFF4"
foreground = "#2E3440"
dim_foreground = "#4C566A"

[colors.cursor]
text = "#ECEFF4"
cursor = "#2E3440"

[colors.vi_mode_cursor]
text = "#ECEFF4"
cursor = "#2E3440"

[colors.selection]
text = "CellForeground"
background = "#D8DEE9"

[colors.normal]
black = "#D8DEE9"
red = "#BF616A"
green = "#8CA97E"
yellow = "#C5A572"
blue = "#5E81AC"
magenta = "#A27BA5"
cyan = "#76A8B8"
white = "#4C566A"

[colors.bright]
black = "#E5E9F0"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#2E3440"

[colors.dim]
black = "#CFD6DD"
red = "#A7525C"
green = "#7C906B"
yellow = "#B89A6A"
blue = "#6D8FB2"
magenta = "#8F7A99"
cyan = "#6E9BA6"
white = "#55606C"
