# Light

[colors]
[colors.primary]
background = '#d0d1d6'
foreground = '#4c505e'

# Normal colors
[colors.normal]
black   = '#a0a8b7'
red     = '#f52a65'
green   = '#587539'
yellow  = '#8c6c3e'
blue    = '#2e7de9'
magenta = '#9854f1'
cyan    = '#007197'
white   = '#4c505e'

# Bright colors
[colors.bright]
black   = '#b8c0d0'
red     = '#ff6b81'
green   = '#76946a'
yellow  = '#c4a15a'
blue    = '#6ca4f8'
magenta = '#b877f2'
cyan    = '#089ec6'
white   = '#24283b'

[colors.selection]
background = '#99a7df'
